---
output:
  pdf_document: default
  bookdown::pdf_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface {-}
Livestock Breeding and Genomics is a masters course taught in the Institute of Agricultural Sciences at ETH Zurich. The aim of this course is to introduce the basic concepts of livestock breeding and genomics to the students. 

## Prerequisites {-}
There are no explicit prerequisites for this course. All required concepts are explained during this course. Although basic knowledge in the following areas is definitely helpful for this course. 

* __Linear Algebra__: Basic properties of and basic operations with vectors and matrices
* __Statistics__: Simple linear models and least squares
* __R__: Basics of how to work with data and how to do simple computations 

## Goals {-}
The following goals are taken from the teaching system at ETH. The students are able to set up design matrices, the additive genetic relationship matrix and its inverse as well as the mixed model equations to estimate BLUP breeding values. The concept of BLUP breeding values are also extended to genomic selection. All concepts introduced during this course are not only presented during the lecture, but students are expected to work with the concepts on small example problems.

## Exam {-}
There will be a written exam during the lecture of the last week of the semester. The exam is going to be an open-book exam. All material that seams helpful to students will be allowed. 

## Lecture Notes {-}
These lecture notes contain all the relevant material for the exam. In the first two chapters, the necessary tools to work through the material of the course are introduced briefly. Those tools consist of linear algebra and R. These chapters are mostly left to students to work through by themselves. Different students have different levels of skills in the topics of linear algebra and R. Hence not every student needs to go through the presented material at the same depth. 
