---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains lists of additional material.


## Slides

```{r slides-table, echo=FALSE}
s_sl_url <- 'https://charlotte-ngs.github.io/lbgfs2020/sl/'
tbl_sl <- tibble::tibble(Nr    = c(1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 8, 9, 9, 10),
                         Date    = c(
                           "2020-09-18",
                           "2020-09-25",
                           "2020-09-25",
                           "2020-10-02",
                           "2020-10-09",
                           "2020-10-16",
                           "2020-10-16",
                           "2020-10-23",
                           "2020-10-30",
                           "2020-11-06",
                           "2020-11-06",
                           "2020-11-13",
                           "2020-11-13",
                           "2020-11-20"
                         ),
                         Topic   = c(
                           paste0("[Introduction to Livestock Breeding and Genomics](", s_sl_url, "lbgfs2020_slides_w01_intro_lbg.pdf)", collapse = ''),
                           paste0("[Review of Quantitative Genetics](", s_sl_url, "lbgfs2020_slides_w02_basics_qg.pdf)", collapse = ''),
                           paste0("[Introduction To RMarkdown](", s_sl_url, "20200925_intro_rmarkdown.pdf)", collapse = ''),
                           paste0("[Genetic Evaluation](", s_sl_url, "lbgfs2020_slides_w03_gen-eval.pdf)", collapse = ''),
                           paste0("[BLUP](", s_sl_url, "lbgfs2020_slides_w04_blup.pdf)", collapse = ''),
                           paste0("[Genetic Covariance](", s_sl_url, "lbgfs2020_slides_gencov.pdf)", collapse = ''),
                           paste0("[Numerator Relationship Matrix](", s_sl_url, "lbgfs2020_slides_numrelmat.pdf)", collapse = ''),
                           paste0("[Invers NRM](", s_sl_url, "lbgfs2020_slides_invnumrelmat.pdf)", collapse = ''),
                           paste0("[Computation of Inbreeding](", s_sl_url, "lbgfs2020_slides_inbreeding.pdf)", collapse = ''),
                           paste0("[Variance and Inbreeding](", s_sl_url, "lbgfs2020_slides_var_inb.pdf)", collapse = ''),
                           paste0("[Additional Aspects of BLUP](", s_sl_url, "lbgfs2019_slides_additional_aspects.pdf)", collapse = ''),
                           paste0("[Mulitple Traits](", s_sl_url, "lbgfs2020_slides_multiple_traits.pdf)", collapse = ''),
                           paste0("[Selection Index](", s_sl_url, "lbgfs2020_slides_selection-index.pdf)", collapse = ''),
                           paste0("[Genomic Selection](", s_sl_url, "lbgfs2020_slides_geno_sel.pdf)", collapse = '')
                         ))
knitr::kable(tbl_sl)
```


## Videos

```{r vd-table, echo=FALSE}
tbl_vd <- tibble::tibble(Nr  = c(1, 2, 3, 4, 5, 6, 7, 8, 9),
                         Date = c(
                           "2020-09-18",
                           "2020-09-25",
                           "2020-10-02",
                           "2020-10-09",
                           "2020-10-16",
                           "2020-10-23",
                           "2020-10-30",
                           "2020-11-06",
                           "2020-11-13"
                         ),
                         Topic = c(
                           "[Introduction to Livestock Breeding and Genomics](https://youtu.be/Mkx2ixBoVF4)",
                           "[Review of Quantitative Genetics](https://youtu.be/3nezvbFDDas)",
                           "[Genetic Evaluation](https://youtu.be/J5kTsEz_UCM)",
                           "[BLUP](https://youtu.be/V1A6Yne5maM)",
                           "[Genetic Covariance](https://youtu.be/XAKmasLp8XU)",
                           "[Numerator Relationship Matrix and its Inverse](https://youtu.be/UK3uuVEmrxs)",
                           "[Inverse Numerator Relationship Matrix and Inbreeding](https://youtu.be/Lu1dB-lT6_0)",
                           "[Variance and Inbreeding, Additional Aspects of BLUP](https://youtu.be/1LpR4BLT_K8)",
                           "[Multiple Traits](https://youtu.be/k1R05BjF5qs)"
                         ))
knitr::kable(tbl_vd)
```


## Pictures From Overhead

```{r ohp-table, echo=FALSE}
s_misc_url <- 'https://charlotte-ngs.github.io/lbgfs2020/misc/'
tbl_ohp <- tibble::tibble(Nr = c(1,2,3,4,5,6),
                          Date = c(
                           "2020-09-18",
                           "2020-09-25",
                           "2020-10-02",
                           "2020-10-09",
                           "2020-10-16",
                           "2020-10-23"
                         ),
                         Topic = c(
                           paste0("[Introduction to Livestock Breeding and Genomics](", s_misc_url, "20200918_ohp_lecture01.pdf)", collapse = ''),
                           paste0("[Review of Quantitative Genetics](", s_misc_url, "20200925_ohp_lecture_02.pdf)", collapse = ''),
                           paste0("[Genetic Evaluation](", s_misc_url, "20201002_ohp_lecture_03.pdf)", collapse = ''),
                           "",
                           paste0("[Genetic Covariance](", s_misc_url, "20201016_ohp_lecture_05.pdf)", collapse = ''),
                           paste0("[Numerator Relationship Matrix](", s_misc_url, "20201023_ohp_lecture_06.pdf)", collapse = '')
                         ))
knitr::kable(tbl_ohp)
```

## Notebooks

```{r nb-table, echo=FALSE}
s_nb_url <- 'https://charlotte-ngs.github.io/lbgfs2020/nb/'
tbl_nb <- tibble::tibble(Nr = c(7, 8, 8),
                         Date = c(
                           "2020-10-30",
                           "2020-11-06",
                           "2020-11-06"
                         ),
                         Topic = c(
                           paste0("[Notebook with Decomposition Matrices of Numerator Relationship Matrix](", s_nb_url, "20201030_nm_inv_inb_nb.nb.html)", collapse = ''),
                           paste0("[Notebook on Strings and Factors](", s_nb_url, "20201106_strings_factors.nb.html)", collapse = ''),
                           paste0("[Setting up MME](", s_nb_url, "20201106_mme_setup.nb.html)", collapse = '')
                         ))
knitr::kable(tbl_nb)
```

## Questionnaire

```{r qu-table, echo=FALSE}
s_misc_url <- 'https://charlotte-ngs.github.io/lbgfs2020/misc/'
tbl_misc <- tibble::tibble(Nr  = c(1),
                           Date = c(
                              "2020-09-18"
                           ),
                           Topic = c(
                             paste0("[Questionnaire](", s_misc_url, "20200918_students_questionnaire.pdf)", collapse = '')
                           ))
knitr::kable(tbl_misc)
```

