---
title: "Solutions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Solutions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The following table contains a list with solutions to the exercises.

```{r solution-table, echo=FALSE}
s_sol_url <- 'https://charlotte-ngs.github.io/lbgfs2020/sol/'
tbl_sol <- tibble::tibble(Nr = c(2, 3, 4, 5, 6, 7, 8, 9),
                          Date  = c(
                            "2020-09-25",
                            "2020-10-02",
                            "2020-10-09",
                            "2020-10-16",
                            "2020-10-23",
                            "2020-10-30",
                            "2020-11-06",
                            "2020-11-13"),
                          Topic = c(
                            paste0("[Linear Algebra](", s_sol_url, "lbgfs2020_w02_sol01_linalg.pdf)", collapse = ''),
                            paste0("[Quantitative Genetics](", s_sol_url, "lbgfs2020_w03_sol02.pdf)", collapse = ''),
                            paste0("[Breeding Values](", s_sol_url, "lbgfs2020_w04_sol03.pdf)", collapse = ''),
                            paste0("[Prediction of Breeding Values and Accuracy](", s_sol_url, "lbgfs2020_w05_sol04.pdf)", collapse = ''),
                            paste0("[Sire Model](", s_sol_url, "lbgfs2020_w06_sol05.pdf)", collapse = ''),
                            paste0("[Numerator Relationship Matrix](", s_sol_url, "lbgfs2020_w07_sol06.pdf)", collapse = ''),
                            paste0("[Variance and Inbreeding](", s_sol_url, "lbgfs2020_w08_sol07.pdf)", collapse = ''),
                            paste0("[Additional Aspects of BLUP](", s_sol_url, "lbgfs2019_w09_sol08.pdf)", collapse = '')
                           ))
knitr::kable(tbl_sol)
```
