---
title: "Course Notes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Course Notes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains the list of links pointing to the different chapters in the course notes. 

## Chapters

```{r chpt-table, echo=FALSE}
s_cn_url <- 'https://charlotte-ngs.github.io/lbgfs2020/cn/'
tbl_chpt <- tibble::tibble(Nr      = c(0, 1, 2, 3, 4, 5, 6),
                           Date    = c(
                             "2020-09-18",
                             "2020-09-18",
                             "2020-09-25",
                             "2020-10-02",
                             "2020-10-09",
                             "2020-10-16",
                             "2020-10-23"
                           ),
                           Topic   = c(
                             paste0("[Preface](", s_cn_url, "00_preface.pdf)", collapse = ""),
                             paste0("[Introduction to Livestock Breeding and Genomics](", s_cn_url, "01_intro_lbg.pdf)", collapse = ""),
                             paste0("[Review of Quantitative Genetics](", s_cn_url, "02_intro_qg.pdf)", collapse = ''),
                             paste0("[Genetic Evaluation](", s_cn_url, "03_gen_eval.pdf)", collapse = ''),
                             paste0("[BLUP](", s_cn_url, "04_blup.pdf)", collapse = ''),
                             paste0("[Genetic Covariances](", s_cn_url, "05_gencov.pdf)", collapse = ''),
                             paste0("[Variance and Inbreeding](", s_cn_url, "06_variance_inbreeding.pdf", collapse = '')
                             ))
knitr::kable(tbl_chpt)
```


## Appendix

```{r app-table, echo=FALSE}
tbl_app <- tibble::tibble(Nr    = c("A1", "A2"),
                          Date  = c(
                             "2020-09-18",
                             "2020-09-18"
                           ),
                          Topic = c(
                            paste0("[Linear Algebra](", s_cn_url, "A1_intro_linalg.pdf)", collapse = ""),
                            paste0("[R Programming](", s_cn_url, "A2_intro_rstats.pdf)", collapse = "")
                          ))
knitr::kable(tbl_app)
```

