---
title: "Exercises"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exercises}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The links to the exercises are given in the following table. 

```{r exercise-table, echo=FALSE}
s_ex_url <- 'https://charlotte-ngs.github.io/lbgfs2020/ex/'
tbl_ex <- tibble::tibble(Nr = c(2, 3, 4, 5, 6, 7, 8, 9, 10),
                         Date = c(
                           "2020-09-25",
                           "2020-10-02",
                           "2020-10-09",
                           "2020-10-16",
                           "2020-10-23",
                           "2020-10-30",
                           "2020-11-06",
                           "2020-11-13",
                           "2020-11-20"),
                         Topic  = c(
                           paste0("[Linear Algebra](", s_ex_url, "lbgfs2020_w02_ex01_linalg.pdf)", collapse = ''),
                           paste0("[Quantitative Genetics](", s_ex_url, "lbgfs2020_w03_ex02.pdf)", collapse = ''),
                           paste0("[Breeding Values](", s_ex_url, "lbgfs2020_w04_ex03.pdf)", collapse = ''),
                           paste0("[Prediction of Breeding Values and Accuracy](", s_ex_url, "lbgfs2020_w05_ex04.pdf)", collapse = ''),
                           paste0("[Sire Model](", s_ex_url, "lbgfs2020_w06_ex05.pdf)", collapse = ''),
                           paste0("[Numerator Relationship Matrix](", s_ex_url, "lbgfs2020_w07_ex06.pdf)", collapse = ''),
                           paste0("[Variance and Inbreeding](", s_ex_url, "lbgfs2020_w08_ex07.pdf)", collapse = ''),
                           paste0("[Additional Aspects of BLUP](", s_ex_url, "lbgfs2019_w09_ex08.pdf)", collapse = ''),
                           paste0("[Multi-Trait BLUP](", s_ex_url, "lbgfs2020_w10_ex09.pdf)", collapse = '')
                           ))
knitr::kable(tbl_ex)
```
